// Alert Actions
export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

// VM Actions
export const VM_BUILD_BEGIN = "VM_BUILD_BEGIN";
export const VM_BUILD_SUCCESS = "VM_BUILD_SUCCESS";
export const VM_BUILD_ERROR = "VM_BUILD_ERROR"

export const VM_CONNECT_BEGIN = "VM_CONNECT_BEGIN";
export const VM_CONNECT_SUCCESS = "VM_CONNECT_SUCCESS";
export const VM_CONNECT_ERROR = "VM_CONNECT_ERROR";

export const VM_DESTROY_BEGIN = "VM_DESTROY_BEGIN";
export const VM_DESTROY_SUCCESS = "VM_DESTROY_SUCCESS";
export const VM_DESTROY_ERROR = "VM_DESTROY_ERROR"

// User Actions
export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "REGISTER_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const LOGIN_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

// UI Actions 
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
